version: 2.1

orbs:
  diag: fernfernfern/diag@dev:volatile

executors:
  docker:
    parameters:
      image:
        type: string
        default: python
      tag:
        type: string
        default: latest
    docker:
      - image: circleci/<< parameters.image >>:<< parameters.tag >>
  macos:
    macos:
      xcode: "10.1.0"
  machine:
    machine: true

jobs:
  build:
    parameters:
      executor:
        type: string
        default: docker
    executor: << parameters.executor >>
    steps:
      - run: sleep 10

workflows:
  my-workflow:
    jobs:
      # - build:
      #     pre-steps:
      #     post-steps:
      #       - diag/post-steps
      - build:
          executor: macos
          pre-steps:
            - run: | 
                mkdir -p ~/project/fastlane
                echo fastfile > ~/project/fastlane/Fastfile
                echo appfile > ~/project/fastlane/Appfile
                echo gymfile > ~/project/fastlane/Gymfile
                mkdir -p ~/project/ccidiag.xcodeproj
                echo project > ~/project/ccidiag.xcodeproj/project.pbxproj
            - diag/ios-logs
          post-steps:
            - diag/post-steps